from __future__ import annotations

import re


CONVERSATIONAL_MAP: dict[str, dict[str, str]] = {
    "sama-sama": {
        "English": "You're welcome.",
        "Japanese": "どういたしまして。",
        "Korean": "천만에요.",
        "Chinese (Simplified)": "不客气。",
        "Chinese (Traditional)": "不客氣。",
        "Spanish": "De nada.",
        "French": "De rien.",
        "German": "Gern geschehen.",
        "Arabic": "عفواً.",
        "Russian": "Пожалуйста.",
        "Javanese": "Sami-sami.",
        "Sundanese": "Sami-sami.",
        "Italian": "Prego.",
        "Portuguese": "De nada.",
        "Dutch": "Graag gedaan.",
        "Tagalog": "Walang anuman.",
        "Vietnamese": "Không có chi.",
        "Thai": "ไม่เป็นไรครับ/ค่ะ",
        "Malay": "Sama-sama.",
        "Hindi": "आपका स्वागत है।",
        "Turkish": "Rica ederim.",
        "Ukrainian": "Будь ласка.",
    },
    "semangat": {
        "English": "Keep it up!",
        "Japanese": "がんばって！",
        "Korean": "화이팅!",
        "Chinese (Simplified)": "加油！",
        "Chinese (Traditional)": "加油！",
        "Spanish": "¡Ánimo!",
        "French": "Bon courage !",
        "German": "Viel Erfolg!",
        "Arabic": "بالتوفيق!",
        "Russian": "Удачи!",
        "Javanese": "Semangat!",
        "Sundanese": "Semangat!",
        "Italian": "Forza!",
        "Portuguese": "Força!",
        "Dutch": "Succes!",
        "Tagalog": "Laban lang!",
        "Vietnamese": "Cố lên!",
        "Thai": "สู้ๆ นะครับ/ค่ะ",
        "Malay": "Semangat!",
        "Hindi": "लगे रहो!",
        "Turkish": "Kolay gelsin!",
        "Ukrainian": "Тримайся!",
    },
    "mantap": {
        "English": "Awesome!",
        "Japanese": "素晴らしい！",
        "Korean": "대박!",
        "Chinese (Simplified)": "太棒了！",
        "Chinese (Traditional)": "太棒了！",
        "Spanish": "¡Genial!",
        "French": "Génial !",
        "German": "Großartig!",
        "Arabic": "رائع!",
        "Russian": "Отлично!",
        "Javanese": "Mantep!",
        "Sundanese": "Mantap!",
        "Italian": "Fantastico!",
        "Portuguese": "Demais!",
        "Dutch": "Geweldig!",
        "Tagalog": "Ayos!",
        "Vietnamese": "Tuyệt vời!",
        "Thai": "สุดยอดเลย",
        "Malay": "Mantap!",
        "Hindi": "बहुत बढ़िया!",
        "Turkish": "Harika!",
        "Ukrainian": "Чудово!",
    },
    "selamat datang": {
        "English": "Welcome everyone!",
        "Japanese": "皆さん、ようこそ！",
        "Korean": "여러분, 환영합니다!",
        "Chinese (Simplified)": "欢迎大家！",
        "Chinese (Traditional)": "歡迎大家！",
        "Spanish": "¡Bienvenidos a todos!",
        "French": "Bienvenue à tous !",
        "German": "Willkommen zusammen!",
        "Arabic": "أهلاً وسهلاً بالجميع!",
        "Russian": "Добро пожаловать всем!",
        "Javanese": "Sugeng rawuh sedaya!",
        "Sundanese": "Wilujeng sumping sadayana!",
        "Italian": "Benvenuti a tutti!",
        "Portuguese": "Bem-vindos a todos!",
        "Dutch": "Welkom allemaal!",
        "Tagalog": "Maligayang pagdating sa lahat!",
        "Vietnamese": "Chào mừng mọi người!",
        "Thai": "ยินดีต้อนรับทุกคนครับ/ค่ะ",
        "Malay": "Selamat datang semua!",
        "Hindi": "सभी का स्वागत है!",
        "Turkish": "Herkese hoş geldiniz!",
        "Ukrainian": "Ласкаво просимо всіх!",
    },
    "sampai jumpa": {
        "English": "See you later!",
        "Japanese": "またね！",
        "Korean": "또 만나요!",
        "Chinese (Simplified)": "再见！",
        "Chinese (Traditional)": "再見！",
        "Spanish": "¡Hasta luego!",
        "French": "À bientôt !",
        "German": "Bis bald!",
        "Arabic": "إلى اللقاء!",
        "Russian": "До скорой встречи!",
        "Javanese": "Ngantos kepanggih malih!",
        "Sundanese": "Dugi ka tepang deui!",
        "Italian": "A presto!",
        "Portuguese": "Até logo!",
        "Dutch": "Tot ziens!",
        "Tagalog": "Hanggang sa muli!",
        "Vietnamese": "Hẹn gặp lại!",
        "Thai": "แล้วเจอกันใหม่ครับ/ค่ะ",
        "Malay": "Jumpa lagi!",
        "Hindi": "फिर मिलेंगे!",
        "Turkish": "Görüşmek üzere!",
        "Ukrainian": "До зустрічі!",
    },
    "tidak apa-apa": {
        "English": "No problem.",
        "Japanese": "大丈夫ですよ。",
        "Korean": "괜찮아요.",
        "Chinese (Simplified)": "没关系。",
        "Chinese (Traditional)": "沒關係。",
        "Spanish": "No pasa nada.",
        "French": "Ce n'est rien.",
        "German": "Kein Problem.",
        "Arabic": "لا مشكلة.",
        "Russian": "Ничего страшного.",
        "Javanese": "Mboten napa-napa.",
        "Sundanese": "Teu sawios-wios.",
        "Italian": "Nessun problema.",
        "Portuguese": "Sem problemas.",
        "Dutch": "Geen probleem.",
        "Tagalog": "Walang anuman.",
        "Vietnamese": "Không sao đâu.",
        "Thai": "ไม่เป็นไรครับ/ค่ะ",
        "Malay": "Tak apa-apa.",
        "Hindi": "कोई बात नहीं।",
        "Turkish": "Sorun değil.",
        "Ukrainian": "Нічого страшного.",
    },
    "tunggu sebentar": {
        "English": "Just a moment.",
        "Japanese": "少々お待ちください。",
        "Korean": "잠시만 기다려주세요.",
        "Chinese (Simplified)": "请稍等一下。",
        "Chinese (Traditional)": "請稍等一下。",
        "Spanish": "Un momento, por favor.",
        "French": "Un instant s'il vous plaît.",
        "German": "Einen Moment bitte.",
        "Arabic": "لحظة من فضلك.",
        "Russian": "Подождите минутку.",
        "Javanese": "Sekedhap nggih.",
        "Sundanese": "Sakedap nya.",
        "Italian": "Un momento per favore.",
        "Portuguese": "Um momento, por favor.",
        "Dutch": "Een momentje alsjeblieft.",
        "Tagalog": "Sandali lang po.",
        "Vietnamese": "Xin đợi một chút.",
        "Thai": "รอสักครู่นะครับ/ค่ะ",
        "Malay": "Tunggu sekejap.",
        "Hindi": "एक पल रुकिए।",
        "Turkish": "Bir dakika lütfen.",
        "Ukrainian": "Зачекайте хвилинку.",
    },
    "hati-hati": {
        "English": "Take care!",
        "Japanese": "気をつけてね！",
        "Korean": "조심하세요!",
        "Chinese (Simplified)": "小心点！",
        "Chinese (Traditional)": "小心點！",
        "Spanish": "¡Cuídate!",
        "French": "Prenez soin de vous !",
        "German": "Pass auf dich auf!",
        "Arabic": "انتبه على نفسك!",
        "Russian": "Береги себя!",
        "Javanese": "Ngati-ati ya!",
        "Sundanese": "Kade nya!",
        "Italian": "Fai attenzione!",
        "Portuguese": "Cuidado!",
        "Dutch": "Pas goed op jezelf!",
        "Tagalog": "Ingat ka!",
        "Vietnamese": "Bảo trọng nhé!",
        "Thai": "ดูแลตัวเองด้วยนะครับ/ค่ะ",
        "Malay": "Hati-hati ya!",
        "Hindi": "अपना ध्यान रखना!",
        "Turkish": "Kendine dikkat et!",
        "Ukrainian": "Бережи себе!",
    },
    "halo": {
        "English": "Hello!",
        "Japanese": "こんにちは！",
        "Korean": "안녕하세요!",
        "Chinese (Simplified)": "你好！",
        "Chinese (Traditional)": "你好！",
        "Spanish": "¡Hola!",
        "French": "Bonjour !",
        "German": "Hallo!",
        "Arabic": "مرحباً!",
        "Russian": "Привет!",
        "Javanese": "Sugeng rawuh!",
        "Sundanese": "Sampurasun!",
        "Italian": "Ciao!",
        "Portuguese": "Olá!",
        "Dutch": "Hallo!",
        "Tagalog": "Kamusta!",
        "Vietnamese": "Xin chào!",
        "Thai": "สวัสดีครับ/ค่ะ",
        "Malay": "Halo!",
        "Hindi": "नमस्ते!",
        "Turkish": "Merhaba!",
        "Ukrainian": "Привіт!",
    },
    "hai": {
        "English": "Hi!",
        "Japanese": "こんにちは！",
        "Korean": "안녕!",
        "Chinese (Simplified)": "嗨！",
        "Chinese (Traditional)": "嗨！",
        "Spanish": "¡Hola!",
        "French": "Salut !",
        "German": "Hi!",
        "Arabic": "مرحباً!",
        "Russian": "Привет!",
        "Javanese": "Halo!",
        "Sundanese": "Halo!",
        "Italian": "Ciao!",
        "Portuguese": "Oi!",
        "Dutch": "Hoi!",
        "Tagalog": "Hoy!",
        "Vietnamese": "Chào!",
        "Thai": "หวัดดีครับ/ค่ะ",
        "Malay": "Hai!",
        "Hindi": "नमस्ते!",
        "Turkish": "Selam!",
        "Ukrainian": "Привіт!",
    },
    "apa kabar": {
        "English": "How are you?",
        "Japanese": "お元気ですか？",
        "Korean": "어떻게 지내세요?",
        "Chinese (Simplified)": "你好吗？",
        "Chinese (Traditional)": "你好嗎？",
        "Spanish": "¿Cómo estás?",
        "French": "Comment allez-vous ?",
        "German": "Wie geht es dir?",
        "Arabic": "كيف حالك؟",
        "Russian": "Как дела?",
        "Javanese": "Pripun kabare?",
        "Sundanese": "Kumaha damang?",
        "Italian": "Come stai?",
        "Portuguese": "Como você está?",
        "Dutch": "Hoe gaat het?",
        "Tagalog": "Kumusta ka?",
        "Vietnamese": "Bạn khỏe không?",
        "Thai": "สบายดีไหมครับ/ค่ะ",
        "Malay": "Apa khabar?",
        "Hindi": "आप कैसे हैं?",
        "Turkish": "Nasılsınız?",
        "Ukrainian": "Як справи?",
    },
    "baik": {
        "English": "I'm good.",
        "Japanese": "元気です。",
        "Korean": "잘 지내요.",
        "Chinese (Simplified)": "我很好。",
        "Chinese (Traditional)": "我很好。",
        "Spanish": "Estoy bien.",
        "French": "Je vais bien.",
        "German": "Mir geht's gut.",
        "Arabic": "أنا بخير.",
        "Russian": "Все хорошо.",
        "Javanese": "Sae.",
        "Sundanese": "Pangestu.",
        "Italian": "Sto bene.",
        "Portuguese": "Estou bem.",
        "Dutch": "Goed hoor.",
        "Tagalog": "Mabuti naman.",
        "Vietnamese": "Tôi khỏe.",
        "Thai": "สบายดีครับ/ค่ะ",
        "Malay": "Khabar baik.",
        "Hindi": "मैं ठीक हूँ।",
        "Turkish": "İyiyim.",
        "Ukrainian": "Все добре.",
    },
    "terima kasih": {
        "English": "Thank you!",
        "Japanese": "ありがとうございます！",
        "Korean": "감사합니다!",
        "Chinese (Simplified)": "谢谢！",
        "Chinese (Traditional)": "謝謝！",
        "Spanish": "¡Gracias!",
        "French": "Merci !",
        "German": "Danke!",
        "Arabic": "شكراً!",
        "Russian": "Спасибо!",
        "Javanese": "Matur nuwun!",
        "Sundanese": "Hatur nuhun!",
        "Italian": "Grazie!",
        "Portuguese": "Obrigado!",
        "Dutch": "Bedankt!",
        "Tagalog": "Salamat!",
        "Vietnamese": "Cảm ơn!",
        "Thai": "ขอบคุณครับ/ค่ะ",
        "Malay": "Terima kasih!",
        "Hindi": "धन्यवाद!",
        "Turkish": "Teşekkürler!",
        "Ukrainian": "Дякую!",
    },
    "selamat pagi": {
        "English": "Good morning!",
        "Japanese": "おはようございます！",
        "Korean": "좋은 아침이에요!",
        "Chinese (Simplified)": "早上好！",
        "Chinese (Traditional)": "早安！",
        "Spanish": "¡Buenos días!",
        "French": "Bonjour !",
        "German": "Guten Morgen!",
        "Arabic": "صباح الخير!",
        "Russian": "Доброе утро!",
        "Javanese": "Sugeng enjang!",
        "Sundanese": "Wilujeng enjing!",
        "Italian": "Buongiorno!",
        "Portuguese": "Bom dia!",
        "Dutch": "Goedemorgen!",
        "Tagalog": "Magandang umaga!",
        "Vietnamese": "Chào buổi sáng!",
        "Thai": "อรุณสวัสดิ์ครับ/ค่ะ",
        "Malay": "Selamat pagi!",
        "Hindi": "शुभ प्रभात!",
        "Turkish": "Günaydın!",
        "Ukrainian": "Доброго ранку!",
    },
    "selamat malam": {
        "English": "Good evening!",
        "Japanese": "こんばんは！",
        "Korean": "좋은 저녁이에요!",
        "Chinese (Simplified)": "晚上好！",
        "Chinese (Traditional)": "晚安！",
        "Spanish": "¡Buenas noches!",
        "French": "Bonsoir !",
        "German": "Guten Abend!",
        "Arabic": "مساء الخير!",
        "Russian": "Добрый вечер!",
        "Javanese": "Sugeng dalu!",
        "Sundanese": "Wilujeng wengi!",
        "Italian": "Buonasera!",
        "Portuguese": "Boa noite!",
        "Dutch": "Goedenavond!",
        "Tagalog": "Magandang gabi!",
        "Vietnamese": "Chào buổi tối!",
        "Thai": "สวัสดีตอนค่ำครับ/ค่ะ",
        "Malay": "Selamat malam!",
        "Hindi": "शुभ संध्या!",
        "Turkish": "İyi akşamlar!",
        "Ukrainian": "Доброго вечора!",
    },
    "maaf": {
        "English": "Sorry.",
        "Japanese": "すみません。",
        "Korean": "죄송합니다.",
        "Chinese (Simplified)": "对不起。",
        "Chinese (Traditional)": "對不起。",
        "Spanish": "Lo siento.",
        "French": "Désolé.",
        "German": "Entschuldigung.",
        "Arabic": "آسف.",
        "Russian": "Извините.",
        "Javanese": "Nyuwun pangapunten.",
        "Sundanese": "Hapunten.",
        "Italian": "Mi dispiace.",
        "Portuguese": "Desculpe.",
        "Dutch": "Sorry.",
        "Tagalog": "Patawad.",
        "Vietnamese": "Xin lỗi.",
        "Thai": "ขอโทษครับ/ค่ะ",
        "Malay": "Maaf.",
        "Hindi": "माफ़ कीजिए।",
        "Turkish": "Özür dilerim.",
        "Ukrainian": "Вибачте.",
    },
}

CONVERSATIONAL_ALIASES: dict[str, str] = {
    "helo": "halo",
    "hello": "halo",
    "halo halo": "halo",
    "halo semua": "halo",
    "halo kawan": "halo",
    "halo teman teman": "halo",
    "halo temen temen": "halo",
    "halo guys": "halo",
    "hai guys": "hai",
    "hai semua": "hai",
    "hi": "hai",
    "hey": "hai",
    "gimana kabarnya": "apa kabar",
    "apa kabar semuanya": "apa kabar",
    "apa kabar kalian": "apa kabar",
    "kabar baik": "baik",
    "baik baik saja": "baik",
    "aku baik": "baik",
    "saya baik": "baik",
    "baik kok": "baik",
    "alhamdulillah baik": "baik",
    "makasih": "terima kasih",
    "makasih banyak": "terima kasih",
    "makasih ya": "terima kasih",
    "makasi": "terima kasih",
    "terima kasih banyak": "terima kasih",
    "terima kasih ya": "terima kasih",
    "terimakasih": "terima kasih",
    "trims": "terima kasih",
    "sama sama": "sama-sama",
    "sama sama ya": "sama-sama",
    "sama-sama ya": "sama-sama",
    "sama2": "sama-sama",
    "terima kasih kembali": "sama-sama",
    "makasih kembali": "sama-sama",
    "semangat ya": "semangat",
    "semangat yaa": "semangat",
    "semangat semuanya": "semangat",
    "ayo semangat": "semangat",
    "tetap semangat": "semangat",
    "mantap sekali": "mantap",
    "mantap banget": "mantap",
    "mantap jiwa": "mantap",
    "keren": "mantap",
    "keren banget": "mantap",
    "keren sekali": "mantap",
    "selamat datang semuanya": "selamat datang",
    "selamat datang kawan-kawan": "selamat datang",
    "selamat datang kawan": "selamat datang",
    "selamat datang teman-teman": "selamat datang",
    "sampai jumpa lagi": "sampai jumpa",
    "sampai ketemu lagi": "sampai jumpa",
    "sampai nanti": "sampai jumpa",
    "dadah": "sampai jumpa",
    "dadah semuanya": "sampai jumpa",
    "dah semuanya": "sampai jumpa",
    "bye bye": "sampai jumpa",
    "gak apa-apa": "tidak apa-apa",
    "nggak apa-apa": "tidak apa-apa",
    "gapapa": "tidak apa-apa",
    "gak papa": "tidak apa-apa",
    "sebentar ya": "tunggu sebentar",
    "sebentar": "tunggu sebentar",
    "tunggu ya": "tunggu sebentar",
    "tunggu dulu": "tunggu sebentar",
    "tunggu sebentar ya": "tunggu sebentar",
    "hati-hati ya": "hati-hati",
    "hati-hati di jalan": "hati-hati",
    "pagi": "selamat pagi",
    "pagi semua": "selamat pagi",
    "malam": "selamat malam",
    "malam semua": "selamat malam",
    "sorry": "maaf",
    "sori": "maaf",
    "minta maaf": "maaf",
}

from lumacaption.mt.slang_normalizer import (
    ALL_SLANG_RULES,
    normalize_indonesian_slang,
    split_into_sentences,
)

INDONESIAN_SLANG_MAP = ALL_SLANG_RULES

