from __future__ import annotations

import re


# Multi-word phrase rules (processed before single-word rules)
PHRASE_SLANG_RULES: list[tuple[re.Pattern, str]] = [
    (re.compile(r"\blagi\s+otw\b", re.IGNORECASE), "sedang di jalan"),
    (re.compile(r"\botw\b", re.IGNORECASE), "sedang di jalan"),
    (re.compile(r"\blagi\s+ngapain\b", re.IGNORECASE), "sedang apa"),
    (re.compile(r"\bmantap\s+jiwa\b", re.IGNORECASE), "luar biasa"),
    (re.compile(r"\bkeren\s+abis\b", re.IGNORECASE), "sangat keren"),
    (re.compile(r"\bbikin\s+pusing\s+aja\b", re.IGNORECASE), "sangat membingungkan"),
    (re.compile(r"\bbikin\s+pusing\b", re.IGNORECASE), "membingungkan"),
    (re.compile(r"\bgak\s+kelar-kelar|ga\s+kelar-kelar\b", re.IGNORECASE), "tidak pernah selesai"),
    (re.compile(r"\bkelar-kelar\b", re.IGNORECASE), "pernah selesai"),
    (re.compile(r"\bjangan\s+baper\b", re.IGNORECASE), "jangan tersinggung"),
    (re.compile(r"\bmager\s+banget\s+(?:gue|gw|gua|gwa)\b", re.IGNORECASE), "saya sangat malas"),
    (re.compile(r"\bmager\s+banget\b", re.IGNORECASE), "sangat malas"),
    (re.compile(r"\bkepo\s+banget(?:\s+sih)?\s+(?:lu|lo|elu)\s+jadi\s+orang\b", re.IGNORECASE), "kamu terlalu ingin tahu"),
    (re.compile(r"\bkepo\s+banget(?:\s+sih)?\s+(?:lu|lo|elu)\b", re.IGNORECASE), "kamu terlalu ingin tahu"),
    (re.compile(r"\bkepo\s+banget\b", re.IGNORECASE), "terlalu ingin tahu"),
    (re.compile(r"\bkocak\s+banget\b", re.IGNORECASE), "sangat lucu"),
    (re.compile(r"\bbikin\s+ngakak\b", re.IGNORECASE), "membuat tertawa"),
    (re.compile(r"\bgaskeun\s+(?:bro|cuy|bray|kawan)\b", re.IGNORECASE), "ayo kawan,"),
    (re.compile(r"\bgaskeun\b", re.IGNORECASE), "ayo mulai"),
    (re.compile(r"\brertain\s+musuhnya|ratain\s+musuhnya\b", re.IGNORECASE), "kalahkan musuhnya"),
    (re.compile(r"\brertain|ratain\b", re.IGNORECASE), "kalahkan"),
    (re.compile(r"\bhoki\s+parah\b", re.IGNORECASE), "sangat beruntung"),
    (re.compile(r"\bgabut\s+parah\b", re.IGNORECASE), "sangat bosan"),
    (re.compile(r"\bsantuy\s+aja|woles\s+aja\b", re.IGNORECASE), "santai saja"),
    (re.compile(r"\bmabar\s+game\s+bareng\b", re.IGNORECASE), "bermain game bersama"),
    (re.compile(r"\bmabar\s+bareng\b", re.IGNORECASE), "bermain bersama"),
    (re.compile(r"\bmabar\b", re.IGNORECASE), "bermain bersama"),
    (re.compile(r"\b(?:makasih\s+banyak|terima\s+kasih\s+banyak)\b", re.IGNORECASE), "terima kasih banyak"),
    (re.compile(r"\b(?:makasih|terima\s+kasih)\s+ya\b", re.IGNORECASE), "terima kasih"),
    (re.compile(r"\bsama[- ]sama\s+ya\b", re.IGNORECASE), "sama-sama"),
    (re.compile(r"\bhati[- ]hati\s+di\s+jalan\b", re.IGNORECASE), "hati-hati di jalan"),
    (re.compile(r"\btunggu\s+(?:sebentar|dulu|bentar)\b", re.IGNORECASE), "tunggu sebentar"),
    (re.compile(r"\b(?:gak|ga|gk)\s+usah\b", re.IGNORECASE), "tidak usah"),
    (re.compile(r"\b(?:gak|ga|gk)\s+bisa\b", re.IGNORECASE), "tidak bisa"),
    (re.compile(r"\b(?:gak|ga|gk)\s+mau\b", re.IGNORECASE), "tidak mau"),
    (re.compile(r"\b(?:gak|ga|gk)\s+ada\b", re.IGNORECASE), "tidak ada"),
    (re.compile(r"\b(?:gak|ga|gk)\s+tau\b", re.IGNORECASE), "tidak tahu"),
    (re.compile(r"\bapa\s+kabar(?:\s+semuanya|\s+kalian)?\b", re.IGNORECASE), "apa kabar"),
    (re.compile(r"\bselamat\s+datang(?:\s+semuanya|\s+kawan|\s+teman-teman)?\b", re.IGNORECASE), "selamat datang"),
    (re.compile(r"\bsampai\s+(?:jumpa|ketemu)(?:\s+lagi)?\b", re.IGNORECASE), "sampai jumpa"),
    (re.compile(r"\s+sumpah\b", re.IGNORECASE), ", sumpah"),
]

# Single-word slang rules
WORD_SLANG_RULES: list[tuple[re.Pattern, str]] = [
    # Pronouns & addresses
    (re.compile(r"\b(?:gue|gw|gua|gwa|ogut|ane|aing)\b", re.IGNORECASE), "saya"),
    (re.compile(r"\b(?:lu|lo|elu|loe|ente|maneh)\b", re.IGNORECASE), "kamu"),
    (re.compile(r"\b(?:sampeyan|panjenengan)\b", re.IGNORECASE), "Anda"),
    (re.compile(r"\b(?:doi|doy)\b", re.IGNORECASE), "dia"),
    (re.compile(r"\b(?:ayank|ayang|beb|baby)\b", re.IGNORECASE), "sayang"),
    (re.compile(r"\b(?:cuy|bro|bray|gan|agan|sob|ngab|lur|dab)\b", re.IGNORECASE), "kawan"),
    (re.compile(r"\b(?:sista|sis)\b", re.IGNORECASE), "saudari"),
    (re.compile(r"\b(?:guys|gaes|rek)\b", re.IGNORECASE), "teman-teman"),
    (re.compile(r"\b(?:temen-temen)\b", re.IGNORECASE), "teman-teman"),
    (re.compile(r"\b(?:temen)\b", re.IGNORECASE), "teman"),
    (re.compile(r"\b(?:bocil|bocah)\b", re.IGNORECASE), "anak kecil"),
    (re.compile(r"\b(?:bokap|babeh)\b", re.IGNORECASE), "ayah"),
    (re.compile(r"\b(?:nyokap|emak)\b", re.IGNORECASE), "ibu"),
    (re.compile(r"\b(?:ortu)\b", re.IGNORECASE), "orang tua"),
    (re.compile(r"\b(?:adek)\b", re.IGNORECASE), "adik"),

    # Common slang verbs & actions
    (re.compile(r"\b(?:mager)\b", re.IGNORECASE), "malas bergerak"),
    (re.compile(r"\b(?:baper)\b", re.IGNORECASE), "tersinggung"),
    (re.compile(r"\b(?:kepo)\b", re.IGNORECASE), "penasaran"),
    (re.compile(r"\b(?:santuy|woles)\b", re.IGNORECASE), "santai"),
    (re.compile(r"\b(?:gaskeun|gaspol|skuy|kuy)\b", re.IGNORECASE), "ayo mulai"),
    (re.compile(r"\b(?:mabar)\b", re.IGNORECASE), "main bersama"),
    (re.compile(r"\b(?:nobar)\b", re.IGNORECASE), "nonton bersama"),
    (re.compile(r"\b(?:nongkrong|nongki)\b", re.IGNORECASE), "berkumpul"),
    (re.compile(r"\b(?:ngopi)\b", re.IGNORECASE), "minum kopi"),
    (re.compile(r"\b(?:jajan)\b", re.IGNORECASE), "membeli camilan"),
    (re.compile(r"\b(?:gabut)\b", re.IGNORECASE), "bosan"),
    (re.compile(r"\b(?:kocak)\b", re.IGNORECASE), "lucu"),
    (re.compile(r"\b(?:ngakak)\b", re.IGNORECASE), "tertawa"),
    (re.compile(r"\b(?:hoki)\b", re.IGNORECASE), "beruntung"),
    (re.compile(r"\b(?:curhat)\b", re.IGNORECASE), "bercerita"),
    (re.compile(r"\b(?:nemenin|nemennin)\b", re.IGNORECASE), "menemani"),
    (re.compile(r"\b(?:ngoding)\b", re.IGNORECASE), "menulis kode"),
    (re.compile(r"\b(?:omongin)\b", re.IGNORECASE), "bicarakan"),
    (re.compile(r"\b(?:ngomong)\b", re.IGNORECASE), "berbicara"),
    (re.compile(r"\b(?:ngobrol)\b", re.IGNORECASE), "mengobrol"),
    (re.compile(r"\b(?:ngerti)\b", re.IGNORECASE), "mengerti"),
    (re.compile(r"\b(?:nyoba|nyobain)\b", re.IGNORECASE), "mencoba"),
    (re.compile(r"\b(?:nyari|nyariin)\b", re.IGNORECASE), "mencari"),
    (re.compile(r"\b(?:liat|ngeliat)\b", re.IGNORECASE), "melihat"),
    (re.compile(r"\b(?:dengerin|denger)\b", re.IGNORECASE), "mendengarkan"),
    (re.compile(r"\b(?:pake)\b", re.IGNORECASE), "memakai"),
    (re.compile(r"\b(?:bikin)\b", re.IGNORECASE), "membuat"),
    (re.compile(r"\b(?:dapet)\b", re.IGNORECASE), "dapat"),
    (re.compile(r"\b(?:sampe)\b", re.IGNORECASE), "sampai"),
    (re.compile(r"\b(?:kelar)\b", re.IGNORECASE), "selesai"),
    (re.compile(r"\b(?:ngelag|lag)\b", re.IGNORECASE), "tersendat"),
    (re.compile(r"\b(?:nanya|nanyain)\b", re.IGNORECASE), "bertanya"),
    (re.compile(r"\b(?:nolak)\b", re.IGNORECASE), "menolak"),
    (re.compile(r"\b(?:nerima)\b", re.IGNORECASE), "menerima"),
    (re.compile(r"\b(?:nemu|nemuin)\b", re.IGNORECASE), "menemukan"),
    (re.compile(r"\b(?:nulis)\b", re.IGNORECASE), "menulis"),
    (re.compile(r"\b(?:nonton)\b", re.IGNORECASE), "menonton"),
    (re.compile(r"\b(?:nunggu|nungguin)\b", re.IGNORECASE), "menunggu"),
    (re.compile(r"\b(?:nelpon|nelfon)\b", re.IGNORECASE), "menelepon"),
    (re.compile(r"\b(?:ngetik)\b", re.IGNORECASE), "mengetik"),
    (re.compile(r"\b(?:ngecek)\b", re.IGNORECASE), "memeriksa"),
    (re.compile(r"\b(?:ngerjain)\b", re.IGNORECASE), "mengerjakan"),
    (re.compile(r"\b(?:ngerasa)\b", re.IGNORECASE), "merasa"),
    (re.compile(r"\b(?:ngebantu)\b", re.IGNORECASE), "membantu"),
    (re.compile(r"\b(?:ngebahas)\b", re.IGNORECASE), "membahas"),
    (re.compile(r"\b(?:ngebeli)\b", re.IGNORECASE), "membeli"),
    (re.compile(r"\b(?:ngejelasin)\b", re.IGNORECASE), "menjelaskan"),
    (re.compile(r"\b(?:ngingetin)\b", re.IGNORECASE), "mengingatkan"),
    (re.compile(r"\b(?:ngirim|ngirimin)\b", re.IGNORECASE), "mengirim"),
    (re.compile(r"\b(?:ngasih)\b", re.IGNORECASE), "memberi"),
    (re.compile(r"\b(?:ngambil)\b", re.IGNORECASE), "mengambil"),
    (re.compile(r"\b(?:ngeluh)\b", re.IGNORECASE), "mengeluh"),
    (re.compile(r"\b(?:ngambek)\b", re.IGNORECASE), "merajuk"),
    (re.compile(r"\b(?:nginep)\b", re.IGNORECASE), "menginap"),
    (re.compile(r"\b(?:ngeles)\b", re.IGNORECASE), "berdalih"),
    (re.compile(r"\b(?:ngegas)\b", re.IGNORECASE), "emosi"),
    (re.compile(r"\b(?:nyalain)\b", re.IGNORECASE), "menyalakan"),
    (re.compile(r"\b(?:matiin)\b", re.IGNORECASE), "mematikan"),
    (re.compile(r"\b(?:benerin)\b", re.IGNORECASE), "memperbaiki"),
    (re.compile(r"\b(?:rapiin)\b", re.IGNORECASE), "merapikan"),
    (re.compile(r"\b(?:beresin)\b", re.IGNORECASE), "membereskan"),
    (re.compile(r"\b(?:bersihin)\b", re.IGNORECASE), "membersihkan"),
    (re.compile(r"\b(?:rebahan)\b", re.IGNORECASE), "berbaring"),
    (re.compile(r"\b(?:pansos)\b", re.IGNORECASE), "panjat sosial"),
    (re.compile(r"\b(?:salfok)\b", re.IGNORECASE), "salah fokus"),
    (re.compile(r"\b(?:gercep)\b", re.IGNORECASE), "gerak cepat"),
    (re.compile(r"\b(?:kudet)\b", re.IGNORECASE), "kurang informasi"),
    (re.compile(r"\b(?:halu)\b", re.IGNORECASE), "berkhayal"),
    (re.compile(r"\b(?:cuan)\b", re.IGNORECASE), "keuntungan"),
    (re.compile(r"\b(?:bokek)\b", re.IGNORECASE), "tidak punya uang"),
    (re.compile(r"\b(?:tajir|holkay|sultan)\b", re.IGNORECASE), "orang kaya"),
    (re.compile(r"\b(?:kicep)\b", re.IGNORECASE), "terdiam"),
    (re.compile(r"\b(?:mingkem)\b", re.IGNORECASE), "diam"),
    (re.compile(r"\b(?:melongo)\b", re.IGNORECASE), "tercengang"),
    (re.compile(r"\b(?:cengo)\b", re.IGNORECASE), "bengong"),
    (re.compile(r"\b(?:ilfil)\b", re.IGNORECASE), "hilang rasa suka"),
    (re.compile(r"\b(?:salting)\b", re.IGNORECASE), "salah tingkah"),
    (re.compile(r"\b(?:zonk)\b", re.IGNORECASE), "hampa"),
    (re.compile(r"\b(?:japri)\b", re.IGNORECASE), "pesan pribadi"),
    (re.compile(r"\b(?:gebetan)\b", re.IGNORECASE), "orang yang ditaksir"),
    (re.compile(r"\b(?:ogah|emoh)\b", re.IGNORECASE), "tidak mau"),

    # Adverbs, degree & intensifiers
    (re.compile(r"\b(?:bgt|buanget)\b", re.IGNORECASE), "sangat"),
    (re.compile(r"\b(?:banget)\b", re.IGNORECASE), "sekali"),
    (re.compile(r"\b(?:parah)\b", re.IGNORECASE), "sekali"),
    (re.compile(r"\b(?:beneran)\b", re.IGNORECASE), "sungguh"),
    (re.compile(r"\b(?:bener)\b", re.IGNORECASE), "benar"),
    (re.compile(r"\b(?:emang|emg)\b", re.IGNORECASE), "memang"),
    (re.compile(r"\b(?:cuman|cm|cma)\b", re.IGNORECASE), "hanya"),

    # Negation, time & interrogatives
    (re.compile(r"\b(?:gak|ga|gk|nggak|ngga|kagak|ndak)\b", re.IGNORECASE), "tidak"),
    (re.compile(r"\b(?:udah|uda|udh)\b", re.IGNORECASE), "sudah"),
    (re.compile(r"\b(?:belom|blm|blom)\b", re.IGNORECASE), "belum"),
    (re.compile(r"\b(?:lagi|lg)\b", re.IGNORECASE), "sedang"),
    (re.compile(r"\b(?:kalo|kl)\b", re.IGNORECASE), "kalau"),
    (re.compile(r"\b(?:abis|abs)\b", re.IGNORECASE), "habis"),
    (re.compile(r"\b(?:terus|trs)\b", re.IGNORECASE), "lalu"),
    (re.compile(r"\b(?:gimana|gmn)\b", re.IGNORECASE), "bagaimana"),
    (re.compile(r"\b(?:kenape|knp)\b", re.IGNORECASE), "kenapa"),
    (re.compile(r"\b(?:ngapain|ngapa)\b", re.IGNORECASE), "sedang apa"),
    (re.compile(r"\b(?:ntar)\b", re.IGNORECASE), "nanti"),
    (re.compile(r"\b(?:malem)\b", re.IGNORECASE), "malam"),
    (re.compile(r"\b(?:makasih|makasi|trims|tq|thx)\b", re.IGNORECASE), "terima kasih"),
    (re.compile(r"\b(?:gapapa|gpp)\b", re.IGNORECASE), "tidak apa-apa"),
    (re.compile(r"\b(?:yodah|yaudah)\b", re.IGNORECASE), "baiklah"),
    (re.compile(r"\b(?:anjir|anjay)\b", re.IGNORECASE), "wah"),
    (re.compile(r"\b(?:mantap|mantep)\b", re.IGNORECASE), "bagus sekali"),
    (re.compile(r"\b(?:aja|aj)\b", re.IGNORECASE), "saja"),
    (re.compile(r"\b(?:yuk|yuks)\b", re.IGNORECASE), "ayo"),
    (re.compile(r"\b(?:capek|cape)\b", re.IGNORECASE), "lelah"),
    (re.compile(r"\b(?:laper)\b", re.IGNORECASE), "lapar"),
    (re.compile(r"\b(?:ngantuk)\b", re.IGNORECASE), "mengantuk"),
    (re.compile(r"\b(?:kesel|jengkel)\b", re.IGNORECASE), "kesal"),
    (re.compile(r"\b(?:males)\b", re.IGNORECASE), "malas"),
    (re.compile(r"\b(?:pegel)\b", re.IGNORECASE), "pegal"),
    (re.compile(r"\b(?:seneng)\b", re.IGNORECASE), "senang"),
    (re.compile(r"\b(?:nangis)\b", re.IGNORECASE), "menangis"),
    (re.compile(r"\b(?:ketawa)\b", re.IGNORECASE), "tertawa"),
    (re.compile(r"\b(?:kaget)\b", re.IGNORECASE), "terkejut"),
    (re.compile(r"\b(?:bengong)\b", re.IGNORECASE), "melamun"),
    (re.compile(r"\b(?:degdegan)\b", re.IGNORECASE), "berdebar"),
    (re.compile(r"\b(?:adem)\b", re.IGNORECASE), "sejuk"),
    (re.compile(r"\b(?:anget)\b", re.IGNORECASE), "hangat"),
    (re.compile(r"\b(?:beres)\b", re.IGNORECASE), "selesai"),
]

# Combined list maintaining priority
ALL_SLANG_RULES = PHRASE_SLANG_RULES + WORD_SLANG_RULES


def normalize_indonesian_slang(text: str) -> str:
    """Transform Indonesian colloquial & streamer slang to standard Indonesian before MT."""
    if not text:
        return ""
    normalized = text
    for pattern, replacement in ALL_SLANG_RULES:
        normalized = pattern.sub(replacement, normalized)
    return normalized


def split_into_sentences(text: str) -> list[str]:
    """Split compound utterance into individual sentences by punctuation boundaries."""
    clean = text.strip()
    if not clean:
        return []
    # Match sentences ending with ?, !, or . followed by space or end of string
    raw_parts = re.split(r"(?<=[?!.])\s+", clean)
    sentences = [p.strip() for p in raw_parts if p.strip()]
    return sentences if sentences else [clean]
